### PR TITLE
Implement 'toggle_filefold' action

### PR DESCRIPTION
**Pull request by echasnovski**
This PR adds `toggle_filefold` action: when done, it toggles fold of a file's diagnostics when cursor is anywhere inside a file's fold. So basically, this is like a 'jump' but it performs "file line" action when on "diagnostic line". It is a similar action to `=` shortcut in vim-fugitive.

Name is a bit clunky but I couldn't figure out a more succinct, informative, and robust alternative. "toggle_fold" might be confusing given "open_folds" and "close_folds" deal on all folds and new action might be confused for being "toggle_folds". But of course it is up to you to decide the best name.

As for the default shortcut I went with `za` following the `zM` and `zR` (maybe change this to `zA`?) . If `=` is better, then adding `nowait = true` [here](https://github.com/folke/lsp-trouble.nvim/blob/ecb9c098228bf1f1db01725aeb7ddc74d1a4acd2/lua/trouble/view.lua#L140) might be a good idea to prevent a delay when user has other kemaps starting with `=` (like `=p` from `vim-unimpaired`) but this might lead to a many unexpected issues down the road.

So there are decisions to be made here:
- Action name:
    - Use `toggle_filefold` (or `toggle_file_fold`).
    - Use `toggle_fold`. Possibly rename `open_folds` and `close_folds` to `open_all_folds` and `close_all_folds` to avoid possible user confusion.
- Action default shortcut:
    - Use `za`.
    - Use `zA`.
    - Use `=` and tweak keymap creation code (with possible consequences).

### CODE REVIEW

**Comment by folke** [comment]
Thank you for working on this!
What about `toggle_fold`? (without the `s`).

As for the shortcuts, I will change the `action_keys` so that it can either map to one `string` key value, or a table of multiple values.

Then I would add both as a default for toggling a single fold `za` and `zA`.

I'll also add defaults for `zm` and `zr` to open / close folds.
And `<tab>` to open an item.

What do you think?

**Comment by folke** [comment]
I just added the option to configure multiple bindings: https://github.com/folke/lsp-trouble.nvim/commit/bf8e8ee63c38103fb42de0b889810b584e378962

**Comment by echasnovski** [comment]
Renamed to 'toggle_fold' and changed default bindings to `{"zA", "za"}`.

**Comment by folke** [comment]
Thanks man!

**Pull request merged**
